[package]
name = "factorio-haptics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-debouncer-mini = "0.2.0"
buttplug = "7.0.2"
tokio = "1.27.0"
anyhow = "1.0.70"
